pull_request_rules:
  - name: Auto Merge (package.json)
    conditions:
      - "status-success=ci/circleci: build_dev"
      - base=development
      - files=package.json
      - "#files=1"
    actions:
      delete_head_branch:
        force: false
      merge:
        method: merge

  - name: Auto Merge (yarn.lock)
    conditions:
      - "status-success=ci/circleci: build_dev"
      - base=development
      - files=yarn.lock
      - "#files=1"
    actions:
      delete_head_branch:
        force: false
      merge:
        method: merge

  - name: Auto Merge (yarn.lock, package-lock.json)
    conditions:
      - "status-success=ci/circleci: build_dev"
      - base=development
      - files=package.json
      - files=yarn.lock
      - "#files=2"
    actions:
      delete_head_branch:
        force: false
      merge:
        method: merge

  - name: Auto Merge (Language pack)
    conditions:
      - "status-success=ci/circleci: build_dev"
      - base=development
      - files~=^assets/locales/
    actions:
      delete_head_branch:
        force: false
      merge:
        method: merge

  - name: Auto Merge (OGP Builder)
    conditions:
      - "status-success=ci/circleci: build_dev"
      - base=master
      - files~=^static/ogp/
    actions:
      delete_head_branch:
        force: false
      merge:
        method: merge